---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, bugs, limitations, known issues, enhancements, fixes, tiering' 
summary: 了解BlueXP分层的新增功能。 
---
= BlueXP分层的新增功能
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
了解BlueXP分层的新增功能。



== 2023年7月4日



=== 现在、您可以调整用于将非活动数据上传到对象存储的带宽

激活BlueXP分层后、ONTAP可以使用无限的网络带宽将非活动数据从集群中的卷传输到对象存储。如果您发现分层流量正在影响正常用户工作负载、则可以限制传输期间可使用的带宽量。 https://docs.netapp.com/us-en/bluexp-tiering/task-managing-tiering.html#changing-the-network-bandwidth-available-to-upload-inactive-data-to-object-storage["了解更多信息。"]。



=== "低层"的层事件将显示在通知中心中

现在、如果集群对其冷数据(包括未分层任何数据的集群)的分层不足20%、则分层事件"将其他数据从集群<name>分层到对象存储以提高存储效率"将显示为通知。

此通知是一个"建议"、可帮助您提高系统效率并节省存储成本。它提供了指向的链接 https://bluexp.netapp.com/cloud-tiering-service-tco["BlueXP分层总拥有成本和节省量计算器"^] 以帮助您计算成本节省。



== 2023年4月3日



=== 已删除许可选项卡

已从BlueXP分层界面中删除许可选项卡。现在、您可以从BlueXP分层内部部署信息板访问按需购买(PAYGO)订阅的所有许可。此外、还提供了一个从该页面到BlueXP数字钱包的链接、可用于查看和管理任何BlueXP分层自带许可证(BYOL)。



=== 分层选项卡已重命名并更新了内容

"集群信息板"选项卡已重命名为"集群"、"内部概述"选项卡已重命名为"内部部署信息板"。这些页面添加了一些信息、可帮助您评估是否可以通过其他分层配置优化存储空间。



== 2023年3月5日



=== 现在、您可以为卷生成分层报告

您可以从"层卷"页面下载报告、以便查看所管理集群上所有卷的分层状态。BlueXP分层会生成一个.CSV文件、您可以根据需要查看此文件并将其发送给公司中的其他人员。 https://docs.netapp.com/us-en/bluexp-tiering/task-managing-tiering.html#download-a-tiering-report-for-your-volumes["请参见如何下载分层报告"]。



== 2022年12月6日



=== 连接器出站Internet访问端点更改

由于BlueXP分层发生了变化、您需要更改以下连接器端点才能成功执行BlueXP分层操作：

[cols="50,50"]
|===
| 旧端点 | 新端点 


| https://cloudmanager.cloud.netapp.com | https://api.bluexp.netapp.com 


| https://*.cloudmanager.cloud.netapp.com | https://*.api.bluexp.netapp.com 
|===
请查看的完整端点列表 https://docs.netapp.com/us-en/bluexp-setup-admin/task-set-up-networking-aws.html#outbound-internet-access["AWS"^]， https://docs.netapp.com/us-en/bluexp-setup-admin/task-set-up-networking-google.html#outbound-internet-access["Google Cloud"^]或 https://docs.netapp.com/us-en/bluexp-setup-admin/task-set-up-networking-azure.html#outbound-internet-access["Azure 酒店"^] 云环境。



== 2022年11月6日



=== 拖放以启用BlueXP分层到Azure Blob、Google Cloud Storage和StorageGRID

如果Azure Blob、Google Cloud Storage或StorageGRID 分层目标作为工作环境存在于Canvas上、则可以将本地ONTAP 工作环境拖动到目标上以启动分层设置向导。



== 2022年9月19日



=== 通过分层向导、您可以在分层到S3存储时配置AWS PrivateLink

在先前版本中、通过VPC端点将集群连接到S3存储分段的安全方式非常耗时。现在、您可以按照前提步骤进行操作 https://docs.netapp.com/us-en/bluexp-tiering/task-tiering-onprem-aws.html#configure-your-system-for-a-private-connection-using-a-vpc-endpoint-interface["使用VPC端点接口为系统配置专用连接"]、然后、您可以在"网络连接"页面的分层设置向导期间选择PrivateLink。

https://docs.netapp.com/us-en/bluexp-tiering/task-tiering-onprem-aws.html["查看将非活动数据分层到Amazon S3的要求和步骤"]。



=== 拖放以启用BlueXP分层到Amazon S3

如果Amazon S3分层目标作为工作环境存在于Canvas上、您可以将内部ONTAP 工作环境拖动到目标上以启动分层设置向导。



=== 选择删除MetroCluster 配置中的镜像对象存储时的分层行为

从MetroCluster 配置中删除镜像对象存储时、系统会提示您是否也要删除主对象存储。您可以选择保持主对象存储附加到聚合、也可以选择将其删除。



== 2022年8月3日



=== 可以为集群中的其他聚合配置其他对象存储

Cloud Tiering UI为对象存储配置添加了一组新页面。您可以添加新的对象存储、将多个对象存储连接到聚合以进行FabricPool 镜像、交换主对象存储和镜像对象存储、删除与聚合的对象存储连接等。 https://docs.netapp.com/us-en/bluexp-tiering/task-managing-object-storage.html["详细了解新的对象存储功能。"]



=== 为MetroCluster 配置提供云分层许可证支持

现在、可以与MetroCluster 配置中的集群共享云分层许可证。在这些情况下、您不再需要使用已弃用的FabricPool 许可证。这样可以更轻松地在更多集群上使用"浮动"云分层许可证。 https://docs.netapp.com/us-en/bluexp-tiering/task-licensing-cloud-tiering.html#apply-bluexp-tiering-licenses-to-clusters-in-special-configurations["请参见如何许可和配置这些类型的集群。"]



== 2022年5月3日



=== 为其他集群配置提供Cloud Tiering许可证支持

现在、可以与分层镜像配置(不包括MetroCluster 配置)中的集群以及分层到IBM云对象存储的集群共享云分层许可证。在这些情况下、您不再需要使用已弃用的FabricPool 许可证。这样可以更轻松地在更多集群上使用"浮动"云分层许可证。 https://docs.netapp.com/us-en/bluexp-tiering/task-licensing-cloud-tiering.html#apply-bluexp-tiering-licenses-to-clusters-in-special-configurations["请参见如何许可和配置这些类型的集群。"]
